### ISSUE TITLE
No fallback for browsers without js enabled

### ISSUE THREAD

**Issue by juliankigwana** [Codeinwp/Nivo-Slider-jQuery#244]
Not only is there no fall-back, but all the images are loaded with none displayed. The worst of both worlds for browsers with no js.

I have created a fix for this, which I'm sure can be worked into your code by someone with alittle more js knowledge than I.

``` html
<!-- only one image so that only one is downloaded for non-js browsers -->
 <div id="slider" class="nivoSlider">
       <img src="images/toystory.jpg" alt="" title="This is an example of a caption" />
 </div>
```

``` css
#slider img {
    position:absolute;
    top:0px;
    left:0px;
    /*the display:none needs to be removed to make it work without JS
    //display:none;*/
}
```

``` javascript
$(window).load(function() {
    var images = ' '+
            '<img src="images/up.jpg" alt="" title="This is an <b>example</b> of a caption" /></a>'+
            '<img src="images/walle.jpg" alt="" />'+
            '<img src="images/nemo.jpg" alt=""/>';

    $('#slider').append(images).nivoSlider();
});
```
